# Model Building

## Imports

In [13]:
import pandas as pd
import numpy as np
import pickle
import random

## Set Options

In [28]:
pd.set_option('display.height', 1000)
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

random.seed(129)

## Load Data

In [15]:
df = pickle.load(open('./clean_data/total.pkl', 'rb'))

## Inspect Data

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5235 entries, 0 to 5234
Data columns (total 46 columns):
Player                     5235 non-null object
Club                       5235 non-null object
POS                        5235 non-null object
GP                         5235 non-null int64
GS                         5235 non-null int64
MINS                       5235 non-null int64
G                          5235 non-null int64
A                          5235 non-null int64
SHTS_FP                    5235 non-null int64
SOG                        5235 non-null int64
GWG                        5235 non-null int64
HmG                        5235 non-null int64
RdG                        5235 non-null int64
Gp90                       5235 non-null float64
SCpct                      5235 non-null float64
Year                       5235 non-null int64
Season                     5235 non-null object
GWA                        5235 non-null int64
HmA                        5235 non-null int64
RdA                        5235 non-null int64
Ap90                       5235 non-null float64
SOGpct                     5235 non-null float64
FC                         5235 non-null int64
FS                         5235 non-null int64
OFF                        5235 non-null int64
YC                         5235 non-null int64
RC                         5235 non-null int64
PKG_FP                     5235 non-null int64
PKA_FP                     5235 non-null int64
Last Name                  5235 non-null object
First Name                 5235 non-null object
Base Salary                5235 non-null float64
Guaranteed Compensation    5235 non-null float64
Date                       5235 non-null object
SHTS_GK                    5235 non-null int64
SV                         5235 non-null int64
GA                         5235 non-null int64
GAA                        5235 non-null float64
W                          5235 non-null int64
L                          5235 non-null int64
T                          5235 non-null int64
ShO                        5235 non-null int64
Wpct                       5235 non-null float64
SvPct                      5235 non-null float64
PKG_GK                     5235 non-null int64
PKA_GK                     5235 non-null int64
dtypes: float64(9), int64(30), object(7)
memory usage: 1.9+ MB

In [17]:
pd.concat([df.head(10), df.tail(10)], axis=0)

                Player Club  POS    GP    GS    MINS     G     A  SHTS_FP   SOG  GWG   HmG  RdG  Gp90  SCpct  Year Season  GWA   HmA  RdA  Ap90  SOGpct    FC    FS   OFF   YC   RC  PKG_FP  PKA_FP    Last Name First Name  Base Salary  Guaranteed Compensation        Date  SHTS_GK   SV   GA  GAA    W    L    T  ShO  Wpct  SvPct  PKG_GK  PKA_GK
0       Luciano Emilio   DC    F  29.0  28.0  2410.0  20.0   1.0     79.0  47.0  4.0  12.0  8.0  0.75   25.3  2007    REG  1.0   1.0  0.0  0.04    59.5  35.0  39.0  21.0  2.0  0.0     0.0     0.0       Emilio    Luciano    265000.00                293125.00  2007-08-31      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0    0.0     0.0     0.0
1     Juan Pablo Angel   NY    F  24.0  24.0  2125.0  19.0   5.0     97.0  53.0  5.0  13.0  6.0  0.80   19.6  2007    REG  2.0   3.0  2.0  0.21    54.6  31.0  20.0  42.0  2.0  1.0     5.0     5.0  Pablo Angel       Juan   1500000.00               1593750.00  2007-08-31      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0    0.0     0.0     0.0
2      Taylor Twellman   NE    F  26.0  25.0  2283.0  16.0   3.0     90.0  55.0  5.0   7.0  9.0  0.63   17.8  2007    REG  1.0   2.0  1.0  0.12    61.1  13.0  41.0  21.0  2.0  0.0     0.0     0.0     Twellman     Taylor    325008.00                350008.00  2007-08-31      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0    0.0     0.0     0.0
3        Eddie Johnson   KC    F  24.0  24.0  2149.0  15.0   6.0     75.0  43.0  6.0   8.0  7.0  0.63   20.0  2007    REG  2.0   3.0  3.0  0.25    57.3  21.0  57.0  50.0  6.0  0.0     1.0     1.0      Johnson      Eddie    750000.00                875000.00  2007-08-31      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0    0.0     0.0     0.0
4       Maykel Galindo  CHV    F  28.0  24.0  2021.0  12.0   5.0     55.0  28.0  5.0   8.0  4.0  0.53   21.8  2007    REG  3.0   3.0  2.0  0.22    50.9  44.0  53.0  30.0  6.0  0.0     0.0     0.0      Galindo     Maykel     72500.00                 72500.00  2007-08-31      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0    0.0     0.0     0.0
5           Ante Razov  CHV    F  26.0  24.0  2041.0  11.0   8.0     85.0  42.0  4.0   9.0  2.0  0.49   12.9  2007    REG  4.0   5.0  3.0  0.35    49.4  37.0  33.0  30.0  2.0  0.0     1.0     1.0        Razov       Ante    245000.00                248750.00  2007-08-31      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0    0.0     0.0     0.0
6       Landon Donovan   LA  M-F  25.0  24.0  2191.0   8.0  13.0     44.0  20.0  1.0   5.0  3.0  0.33   18.2  2007    REG  3.0  10.0  3.0  0.53    45.5  19.0  40.0  11.0  3.0  0.0     5.0     6.0      Donovan     Landon    900000.00                900000.00  2007-08-31      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0    0.0     0.0     0.0
7            Ben Olsen   DC    M  24.0  21.0  1881.0   7.0   7.0     29.0  17.0  3.0   5.0  2.0  0.33   24.1  2007    REG  2.0   6.0  1.0  0.33    58.6  49.0  41.0  11.0  8.0  0.0     0.0     0.0        Olsen        Ben    155000.00                177500.00  2007-08-31      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0    0.0     0.0     0.0
8     Alejandro Moreno  CLB    F  29.0  27.0  2357.0   7.0   7.0     54.0  32.0  1.0   2.0  5.0  0.27   13.0  2007    REG  1.0   4.0  3.0  0.27    59.3  54.0  93.0  32.0  3.0  0.0     0.0     0.0       Moreno  Alejandro    120000.00                125000.00  2007-08-31      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0    0.0     0.0     0.0
9         Jaime Moreno   DC    F  21.0  15.0  1439.0   7.0   6.0     34.0  18.0  2.0   5.0  2.0  0.44   20.6  2007    REG  1.0   5.0  1.0  0.38    52.9  24.0  30.0  15.0  3.0  0.0     4.0     4.0       Moreno      Jaime    250000.00                275000.00  2007-08-31      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0    0.0     0.0     0.0
5225    Logan Ketterer  CLB   GK   0.0   0.0     0.0   0.0   0.0      0.0   0.0  0.0   0.0  0.0  0.00    0.0  2017    REG  0.0   0.0  0.0  0.00     0.0   0.0   0.0   0.0  0.0  0.0     0.0     0.0     Ketterer      Logan     53004.00                 53004.00  2017-04-15      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0    0.0     0.0     0.0
5226         Alex Kapp  MIN   GK   0.0   0.0     0.0   0.0   0.0      0.0   0.0  0.0   0.0  0.0  0.00    0.0  2017    REG  0.0   0.0  0.0  0.00     0.0   0.0   0.0   0.0  0.0  0.0     0.0     0.0         Kapp       Alex     53004.00                 53004.00  2017-09-15      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0    0.0     0.0     0.0
5227       Brad Stuver  CLB   GK   0.0   0.0     0.0   0.0   0.0      0.0   0.0  0.0   0.0  0.0  0.00    0.0  2017    REG  0.0   0.0  0.0  0.00     0.0   0.0   0.0   0.0  0.0  0.0     0.0     0.0       Stuver       Brad     80004.00                 80004.00  2017-04-15      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0    0.0     0.0     0.0
5228    Patrick McLain  MIN   GK   0.0   0.0     0.0   0.0   0.0      0.0   0.0  0.0   0.0  0.0  0.00    0.0  2017    REG  0.0   0.0  0.0  0.00     0.0   0.0   0.0   0.0  0.0  0.0     0.0     0.0       McLain    Patrick     80000.00                 80000.00  2017-04-15      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0    0.0     0.0     0.0
5229         Mark Pais  TOR   GK   0.0   0.0     0.0   0.0   0.0      0.0   0.0  0.0   0.0  0.0  0.00    0.0  2017    REG  0.0   0.0  0.0  0.00     0.0   0.0   0.0   0.0  0.0  0.0     0.0     0.0         Pais       Mark     65004.00                 65004.00  2017-04-15      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0    0.0     0.0     0.0
5230  Kendall McIntosh  POR   GK   0.0   0.0     0.0   0.0   0.0      0.0   0.0  0.0   0.0  0.0  0.00    0.0  2017    REG  0.0   0.0  0.0  0.00     0.0   0.0   0.0   0.0  0.0  0.0     0.0     0.0     McIntosh    Kendall     53000.00                 53000.00  2017-04-15      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0    0.0     0.0     0.0
5231     Josh Saunders  ORL   GK   0.0   0.0     0.0   0.0   0.0      0.0   0.0  0.0   0.0  0.0  0.00    0.0  2017    REG  0.0   0.0  0.0  0.00     0.0   0.0   0.0   0.0  0.0  0.0     0.0     0.0     Saunders       Josh    150000.00                150000.00  2017-04-15      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0    0.0     0.0     0.0
5232     Eric Kronberg  MTL   GK   0.0   0.0     0.0   0.0   0.0      0.0   0.0  0.0   0.0  0.0  0.00    0.0  2017    REG  0.0   0.0  0.0  0.00     0.0   0.0   0.0   0.0  0.0  0.0     0.0     0.0     Kronberg       Eric     99999.96                104999.96  2017-04-15      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0    0.0     0.0     0.0
5233    Bryan Meredith  SEA   GK   0.0   0.0     0.0   0.0   0.0      0.0   0.0  0.0   0.0  0.0  0.00    0.0  2017    REG  0.0   0.0  0.0  0.00     0.0   0.0   0.0   0.0  0.0  0.0     0.0     0.0     Meredith      Bryan     66150.00                 66150.00  2017-04-15      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0    0.0     0.0     0.0
5234        Ryan Meara   NY   GK   0.0   0.0     0.0   0.0   0.0      0.0   0.0  0.0   0.0  0.0  0.00    0.0  2017    REG  0.0   0.0  0.0  0.00     0.0   0.0   0.0   0.0  0.0  0.0     0.0     0.0        Meara       Ryan    100008.00                105008.00  2017-04-15      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0    0.0     0.0     0.0

In [26]:
df.sample(20)

                Player Club  POS  GP  GS  MINS  G  A  SHTS_FP  SOG  GWG  HmG  RdG  Gp90  SCpct  Year Season  GWA  HmA  RdA  Ap90  SOGpct  FC  FS  OFF  YC  RC  PKG_FP  PKA_FP  Last Name First Name  Base Salary  Guaranteed Compensation        Date  SHTS_GK  SV  GA   GAA   W  L  T  ShO  Wpct  SvPct  PKG_GK  PKA_GK
1708    Gershon Koffie  VAN    M  29  28  2503  3  2       39   11    1    3    0  0.11    7.7  2012    REG    1    2    0  0.07    28.2  59  70    1   9   0       0       0     Koffie    Gershon      90000.0                 92500.00  2012-05-15        0   0   0  0.00   0  0  0    0   0.0    0.0       0       0
2406   Jason Hernandez   SJ    D  21  19  1679  0  0        0    0    0    0    0  0.00    0.0  2013    REG    0    0    0  0.00     0.0  13   9    0   2   0       0       0  Hernandez      Jason     205000.0                208333.33  2013-05-01        0   0   0  0.00   0  0  0    0   0.0    0.0       0       0
3136    Jack McInerney  CLB    F  22  15  1359  6  1       35   16    3    5    1  0.40   17.1  2015    REG    0    1    0  0.07    45.7  19  15   14   6   0       0       0  McInerney       Jack     270000.0                334166.67  2015-09-15        0   0   0  0.00   0  0  0    0   0.0    0.0       0       0
1111      Pablo Campos  RSL    F  16   3   434  0  1       12    4    0    0    0  0.00    0.0  2010    REG    0    1    0  0.21    33.3  15   7    4   2   0       0       0     Campos      Pablo      78750.0                 83596.72  2010-08-12        0   0   0  0.00   0  0  0    0   0.0    0.0       0       0
4023     Yair Arboleda  HOU    M   1   1    62  0  0        1    0    0    0    0  0.00    0.0  2016    REG    0    0    0  0.00     0.0   0   1    0   0   0       0       0   Arboleda       Yair      62500.0                 62499.96  2016-09-15        0   0   0  0.00   0  0  0    0   0.0    0.0       0       0
2212       Jeb Brovsky  MTL    D  30  29  2610  2  2       14    6    0    1    1  0.07   14.3  2013    REG    0    2    0  0.07    42.9  21  14    1   5   0       0       0    Brovsky        Jeb      80000.0                 84000.00  2013-05-01        0   0   0  0.00   0  0  0    0   0.0    0.0       0       0
4758     Brad Knighton   NE   GK   6   6   540  0  0        0    0    0    0    0  0.00    0.0  2009    REG    0    0    0  0.00     0.0   0   0    0   0   0       0       0   Knighton       Brad      34000.0                 34000.00  2009-09-15       49  36  14  2.33   1  2  3    0  16.7   73.5       0       0
1757       Scott Sealy  DAL    F  16   8   641  2  0       16    6    0    1    1  0.28   12.5  2012    REG    0    0    0  0.00    37.5   8   7    8   0   0       0       0      Sealy      Scott      50004.0                 50004.00  2012-05-15        0   0   0  0.00   0  0  0    0   0.0    0.0       0       0
5143      Tyler Miller  SEA   GK   1   1    90  0  0        0    0    0    0    0  0.00    0.0  2016    REG    0    0    0  0.00     0.0   0   0    0   0   0       0       0     Miller      Tyler      62508.0                 62508.00  2016-05-15        4   2   2  2.00   0  1  0    0   0.0   50.0       0       0
331       Ryan Johnson   SJ    F  28  13  1535  5  1       29   19    1    3    2  0.29   17.2  2008    REG    1    1    0  0.06    65.5  31  24   12   2   0       0       0    Johnson       Ryan      33000.0                 33000.00  2008-10-07        0   0   0  0.00   0  0  0    0   0.0    0.0       0       0
3336      Rafael Ramos  ORL    D  25  24  1998  0  2        8    3    0    0    0  0.00    0.0  2015    REG    1    2    0  0.09    37.5  20  12    2   5   2       0       0      Ramos     Rafael      50000.0                 50000.00  2015-07-15        0   0   0  0.00   0  0  0    0   0.0    0.0       0       0
2230     Julio Morales  CHV    F  17   9   768  2  0       17    8    0    1    1  0.23   11.8  2013    REG    0    0    0  0.00    47.1  14  16    4   2   0       0       0    Morales      Julio      35125.0                 35125.00  2013-05-01        0   0   0  0.00   0  0  0    0   0.0    0.0       0       0
4765      Ben Dragavon  UNK   GK   1   0    61  0  0        0    0    0    0    0  0.00    0.0  2009    REG    0    0    0  0.00     0.0   0   0    0   0   0       0       0   Dragavon        Ben      34000.0                 34000.00  2009-09-15        3   2   1  1.00   0  1  0    0   0.0   66.7       0       0
1382   Quincy Amarikwa  COL    F  15   5   510  1  1       16    4    1    0    1  0.18    6.3  2011    REG    0    1    0  0.18    25.0  14  15    8   1   1       0       0   Amarikwa     Quincy      42000.0                 42000.00  2011-09-01        0   0   0  0.00   0  0  0    0   0.0    0.0       0       0
5064  Donovan Ricketts  ORL   GK  21  21  1890  0  0        0    0    0    0    0  0.00    0.0  2015    REG    0    0    0  0.00     0.0   0   0    0   0   0       0       0   Ricketts    Donovan     260000.0                260000.00  2015-07-15       92  58  32  1.52   7  9  5    3  33.3   63.0       4       4
4606      Jordan Allen  RSL  M-F   2   2   113  0  0        3    1    0    0    0  0.00    0.0  2017    REG    0    0    0  0.00    33.3   2   2    0   0   0       0       0      Allen     Jordan     178000.0                178000.00  2017-04-15        0   0   0  0.00   0  0  0    0   0.0    0.0       0       0
4938       Clint Irwin  COL   GK  32  31  2873  0  0        0    0    0    0    0  0.00    0.0  2013    REG    0    0    0  0.00     0.0   0   0    0   0   0       0       0      Irwin      Clint      35125.0                 35125.00  2013-05-01      132  91  35  1.13  14  9  9   10  43.8   68.9       6       8
5072    Jesse Gonzalez  DAL   GK  11  11   990  0  0        0    0    0    0    0  0.00    0.0  2015    REG    0    0    0  0.00     0.0   0   0    0   0   0       0       0   Gonzalez      Jesse      60000.0                 69375.00  2015-07-15       47  37  10  0.91   7  3  1    5  63.6   78.7       2       4
3342         Sal Zizzo   NY    D  22  10  1032  0  2       16    3    0    0    0  0.00    0.0  2015    REG    0    0    2  0.17    18.8   9   6    1   1   0       0       1      Zizzo        Sal      80850.0                 94896.00  2015-07-15        0   0   0  0.00   0  0  0    0   0.0    0.0       0       0
3507       Mikey Lopez   KC    M   6   5   482  0  0        3    1    0    0    0  0.00    0.0  2015    REG    0    0    0  0.00    33.3  14   4    0   1   0       0       0      Lopez      Mikey     100000.0                172000.00  2015-07-15        0   0   0  0.00   0  0  0    0   0.0    0.0       0       0

### Fix Integer Column Dtypes

In [24]:
# Set Integer Column Dtypes
int_cols = ['GP', 'GS', 'MINS', 'G', 'A', 'SHTS_FP', 'SOG', 'GWG', 
            'HmG', 'RdG', 'Year', 'GWA', 'HmA', 'RdA', 'FC', 'FS', 
            'OFF', 'YC', 'RC', 'PKG_FP', 'PKA_FP', 'SHTS_GK', 'SV',
            'GA', 'W', 'L', 'T', 'ShO', 'PKG_GK', 'PKA_GK']
for col in int_cols:
    df[col] = df[col].astype(int)

In [27]:
df.sample(20)

                Player Club  POS  GP  GS  MINS   G  A  SHTS_FP  SOG  GWG  HmG  RdG  Gp90  SCpct  Year Season  GWA  HmA  RdA  Ap90  SOGpct  FC  FS  OFF  YC  RC  PKG_FP  PKA_FP  Last Name First Name  Base Salary  Guaranteed Compensation        Date  SHTS_GK  SV  GA   GAA  W  L  T  ShO  Wpct  SvPct  PKG_GK  PKA_GK
1574  Michael Nanchoff  VAN    M   5   1   137   0  0        2    0    0    0    0  0.00    0.0  2011    REG    0    0    0  0.00     0.0   3   0    0   0   0       0       0   Nanchoff    Michael      60000.0                 95000.00  2011-09-01        0   0   0  0.00  0  0  0    0   0.0    0.0       0       0
2242      Bobby Convey  TOR    M  24  22  1908   1  4       17    3    0    0    1  0.05    5.9  2013    REG    1    4    0  0.19    17.6  22  32    4   4   0       0       0     Convey      Bobby     200000.0                215000.00  2013-08-01        0   0   0  0.00  0  0  0    0   0.0    0.0       0       0
2110       Conor Casey  PHI    F  31  25  2201  10  5       64   26    3    6    4  0.41   15.6  2013    REG    0    2    3  0.20    40.6  58  26   25   9   0       0       0      Casey      Conor     175000.0                175000.00  2013-05-01        0   0   0  0.00  0  0  0    0   0.0    0.0       0       0
1761     Chad Marshall  CLB    D  24  24  2146   2  0       22    8    0    2    0  0.08    9.1  2012    REG    0    0    0  0.00    36.4  15  15    3   1   0       0       0   Marshall       Chad     310000.0                341250.00  2012-05-15        0   0   0  0.00  0  0  0    0   0.0    0.0       0       0
1120    Peri Marosevic  DAL    F   0   0     0   0  0        0    0    0    0    0  0.00    0.0  2010    REG    0    0    0  0.00     0.0   0   0    0   0   0       0       0  Marosevic       Peri      75000.0                124000.00  2010-08-12        0   0   0  0.00  0  0  0    0   0.0    0.0       0       0
5135       Dan Kennedy   LA   GK   3   2   115   0  0        0    0    0    0    0  0.00    0.0  2016    REG    0    0    0  0.00     0.0   0   0    0   0   0       0       0    Kennedy        Dan     180000.0                195400.00  2016-05-15        7   4   3  1.50  0  0  1    0   0.0   57.1       0       0
1503     Steven Kinney  CHI    D   0   0     0   0  0        0    0    0    0    0  0.00    0.0  2011    REG    0    0    0  0.00     0.0   0   0    0   0   0       0       0     Kinney     Steven      42000.0                 42000.00  2011-09-01        0   0   0  0.00  0  0  0    0   0.0    0.0       0       0
3160    Gabriel Torres  COL  M-F  25  19  1595   4  3       42   14    0    1    3  0.23    9.5  2015    REG    2    1    2  0.17    33.3  20  29   25   1   0       0       0     Torres    Gabriel     262000.0                274500.00  2015-07-15        0   0   0  0.00  0  0  0    0   0.0    0.0       0       0
4791    Andrew Dykstra  CHI   GK  17  17  1530   0  0        0    0    0    0    0  0.00    0.0  2010    REG    0    0    0  0.00     0.0   0   0    0   0   0       0       0    Dykstra     Andrew      40000.0                 40000.00  2010-08-12       80  55  21  1.24  5  6  6    5  29.4   68.8       2       2
914       Sanna Nyassi  SEA    M  14   2   305   0  0        6    1    0    0    0  0.00    0.0  2009    REG    0    0    0  0.00    16.7   8   4    3   2   0       0       0     Nyassi      Sanna      20100.0                 20100.00  2009-09-15        0   0   0  0.00  0  0  0    0   0.0    0.0       0       0
4311     Jordan Harvey  VAN    D  28  28  2509   1  1        8    4    0    1    0  0.04   12.5  2017    REG    1    0    1  0.04    50.0  37  22    1   3   0       0       0     Harvey     Jordan     180000.0                180000.00  2017-04-15        0   0   0  0.00  0  0  0    0   0.0    0.0       0       0
157      Markus Schopp   NY  D-M   5   3   228   0  1        3    1    0    0    0  0.00    0.0  2007    REG    0    0    1  0.39    33.3   8   1    0   1   0       0       0     Schopp     Markus     175000.0                175000.00  2007-08-31        0   0   0  0.00  0  0  0    0   0.0    0.0       0       0
4753     Preston Burpo  COL   GK  11  11   990   0  0        0    0    0    0    0  0.00    0.0  2009    REG    0    0    0  0.00     0.0   0   0    0   0   0       0       0      Burpo    Preston      57872.0                 57871.99  2009-09-15       41  23  16  1.45  1  4  6    1   9.1   56.1       1       1
1294   Veljko Paunovic  PHI    F  17  16  1236   3  3       32   10    0    1    2  0.22    9.4  2011    REG    0    3    0  0.22    31.3  26  21    8   1   0       0       0   Paunovic     Veljko      90000.0                 90000.00  2011-09-01        0   0   0  0.00  0  0  0    0   0.0    0.0       0       0
4621   Ricardo Velazco  RSL    F   9   1   254   0  0        5    1    0    0    0  0.00    0.0  2017    REG    0    0    0  0.00    20.0   9  14    0   2   0       0       0    Velazco    Ricardo      65633.4                 65633.40  2017-04-15        0   0   0  0.00  0  0  0    0   0.0    0.0       0       0
1162     Jason Yeisley  DAL    F   5   0    39   0  0        1    0    0    0    0  0.00    0.0  2010    REG    0    0    0  0.00     0.0   0   1    1   0   0       0       0    Yeisley      Jason      40000.0                 40000.00  2010-08-12        0   0   0  0.00  0  0  0    0   0.0    0.0       0       0
2232        Cam Weaver  HOU    F  22   6   709   2  0       21    5    0    2    0  0.25    9.5  2013    REG    0    0    0  0.00    23.8  22  15    8   1   0       0       0     Weaver        Cam     100000.0                108406.67  2013-05-01        0   0   0  0.00  0  0  0    0   0.0    0.0       0       0
2086        Cam Weaver  HOU    F   9   2   253   0  0        9    4    0    0    0  0.00    0.0  2012    REG    0    0    0  0.00    44.4   6   4    4   1   0       0       0     Weaver        Cam      98175.0                106425.00  2012-05-15        0   0   0  0.00  0  0  0    0   0.0    0.0       0       0
5026     Chris Konopka  TOR   GK   0   0     0   0  0        0    0    0    0    0  0.00    0.0  2014    REG    0    0    0  0.00     0.0   0   0    0   0   0       0       0    Konopka      Chris      60000.0                 60000.00  2014-04-01        0   0   0  0.00  0  0  0    0   0.0    0.0       0       0
776         Corey Ashe  HOU    M  27  13  1250   0  3        5    1    0    0    0  0.00    0.0  2009    REG    1    0    3  0.22    20.0  11  17    5   1   0       0       0       Ashe      Corey      34650.0                 34650.00  2009-09-15        0   0   0  0.00  0  0  0    0   0.0    0.0       0       0

## Correlation

### Plotting

## Modeling